In [1]:
import os
from os import listdir
from os.path import isfile,abspath, join,curdir
import sys
sys.path.insert(0, './common/')
import aggregation
import csv_utils
import pandas as pd

In [2]:
FOLDER = os.path.join('data','submissions')
CURRENT_PATH = abspath(curdir)
FULL_PATH = join(CURRENT_PATH, FOLDER)
onlyfiles = [join(FULL_PATH, f) for f in listdir(FOLDER) if isfile(join(FULL_PATH, f))]
onlyfiles

['E:\\Dropbox\\folch\\UVA\\Applied Machine Learning\\Project_quora\\data\\submissions\\submission_0137PM-November-24-2018.csv',
 'E:\\Dropbox\\folch\\UVA\\Applied Machine Learning\\Project_quora\\data\\submissions\\submission_0230PM-November-25-2018.csv',
 'E:\\Dropbox\\folch\\UVA\\Applied Machine Learning\\Project_quora\\data\\submissions\\submission_0411PM-December-05-2018.csv',
 'E:\\Dropbox\\folch\\UVA\\Applied Machine Learning\\Project_quora\\data\\submissions\\submission_0603PM-November-23-2018.csv',
 'E:\\Dropbox\\folch\\UVA\\Applied Machine Learning\\Project_quora\\data\\submissions\\submission_0604PM-November-23-2018.csv',
 'E:\\Dropbox\\folch\\UVA\\Applied Machine Learning\\Project_quora\\data\\submissions\\submission_0843PM-November-23-2018.csv',
 'E:\\Dropbox\\folch\\UVA\\Applied Machine Learning\\Project_quora\\data\\submissions\\submission_0934PM-November-27-2018.csv']

In [3]:
kaggleScores = [
    0.78603,# submission_0137PM-November-24-2018.csv
    0.78318,# submission_0230PM-November-25-2018.csv
    0.71005,# submission_0411PM-December-05-2018.csv
    0.64885,# submission_0603PM-November-23-2018.csv
    0.69281,# submission_0604PM-November-23-2018.csv
    0.66303,# submission_0843PM-November-23-2018.csv
    0.68705 # submission_0934PM-November-27-2018.csv
]

In [4]:
df = pd.read_csv(onlyfiles[0])

files = onlyfiles[1:]
i = 1
for p in files:
    df = pd.merge(df, pd.read_csv(p), on='test_id', how='inner')
    i += 1
df.columns = ['test_id'] + ['col'+str(j) for j in range(i)]
    
df

       test_id  col0  col1  col2  col3  col4  col5  col6
0           15     1     1     0     0     0     0     0
1           20     0     1     0     0     0     0     0
2           21     0     0     0     1     0     0     0
3           23     0     0     0     0     0     0     0
4           34     0     0     1     1     0     0     0
5           46     0     0     0     0     0     0     0
6           48     0     0     0     1     1     0     0
7           51     0     0     0     1     1     0     0
8           54     0     0     0     0     0     0     0
9           56     0     0     0     0     0     0     0
10          58     1     1     1     0     1     0     0
11          72     1     1     1     1     1     1     0
12          73     1     1     1     0     0     0     0
13          78     0     1     0     0     0     0     0
14          81     0     0     0     0     0     0     0
15          88     1     1     0     1     1     0     0
16          94     0     0     0     0     0     0     0
17         100     1     1     0     0     0     0     1
18         107     1     0     1     1     1     0     1
19         113     1     0     0     0     0     1     0
20         121     0     0     0     0     0     0     0
21         128     1     0     1     0     0     0     0
22         132     0     0     0     1     0     0     0
23         134     0     0     0     0     0     0     0
24         139     0     0     0     1     0     0     1
25         142     0     0     0     0     0     0     0
26         143     1     0     0     1     1     0     0
27         148     0     0     0     1     0     0     0
28         151     0     0     0     1     0     1     1
29         156     0     0     0     0     1     0     0
...        ...   ...   ...   ...   ...   ...   ...   ...
81096   404175     0     0     0     0     1     1     0
81097   404176     1     0     1     1     0     0     0
81098   404177     0     0     0     1     0     0     0
81099   404179     1     0     1     0     0     0     0
81100   404180     0     0     0     1     0     0     0
81101   404181     0     0     0     0     1     0     0
81102   404184     0     0     0     0     0     0     0
81103   404193     0     0     0     0     0     0     1
81104   404203     1     1     1     1     1     0     1
81105   404206     0     0     0     0     0     0     0
81106   404207     0     0     0     1     1     0     1
81107   404209     1     0     1     1     1     0     1
81108   404213     0     0     0     0     0     0     0
81109   404216     1     1     1     1     1     0     0
81110   404217     0     1     0     0     0     0     0
81111   404223     0     0     0     0     0     0     0
81112   404235     0     0     0     1     0     0     0
81113   404236     1     1     0     1     0     0     0
81114   404237     0     0     0     0     0     0     0
81115   404243     1     1     1     0     0     0     1
81116   404247     0     0     0     0     1     0     0
81117   404248     0     0     0     1     0     0     0
81118   404252     1     0     0     1     1     0     0
81119   404254     0     0     0     0     0     0     0
81120   404263     0     1     1     0     0     0     0
81121   404264     0     0     0     0     0     0     0
81122   404265     1     1     1     0     0     1     1
81123   404269     0     1     1     0     1     0     0
81124   404270     1     1     1     1     1     1     0
81125   404278     0     0     0     1     0     0     0

[81126 rows x 8 columns]

In [5]:
#aggregate = aggregation.aggregateAlbert
aggregate = aggregation.aggregateXavi

aggregated = aggregate(df, kaggleScores)

In [6]:
aggregated

       test_id  winner
0           15       0
1           20       0
2           21       0
3           23       0
4           34       0
5           46       0
6           48       0
7           51       0
8           54       0
9           56       0
10          58       0
11          72       1
12          73       0
13          78       0
14          81       0
15          88       0
16          94       0
17         100       0
18         107       1
19         113       0
20         121       0
21         128       0
22         132       0
23         134       0
24         139       0
25         142       0
26         143       0
27         148       0
28         151       0
29         156       0
...        ...     ...
81096   404175       0
81097   404176       0
81098   404177       0
81099   404179       0
81100   404180       0
81101   404181       0
81102   404184       0
81103   404193       0
81104   404203       1
81105   404206       0
81106   404207       0
81107   404209       1
81108   404213       0
81109   404216       1
81110   404217       0
81111   404223       0
81112   404235       0
81113   404236       0
81114   404237       0
81115   404243       0
81116   404247       0
81117   404248       0
81118   404252       0
81119   404254       0
81120   404263       0
81121   404264       0
81122   404265       0
81123   404269       0
81124   404270       1
81125   404278       0

[81126 rows x 2 columns]

In [7]:
csv_utils.create_csvs(aggregated['winner'], aggregated['test_id'])

saved in:  E:\Dropbox\folch\UVA\Applied Machine Learning\Project_quora\data\submissions\submission_0431PM-December-05-2018.csv